package com.restaurationaws.reservationfinalizationservice.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "RestaurantReservation")
public class Reservation {

    private String reservationId;
    private String date;
    private String email;
    private String firstName;
    private String lastName;
    private String tokenId;
    private String nummberOfGuests;
    private String status;


    public Reservation() {
    }
    public Reservation(String reservationId, String date, String email, String firstName, String lastName, String tokenId, String nummberOfGuests) {
        this.reservationId = reservationId;
        this.date = date;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.tokenId = tokenId;
        this.nummberOfGuests = nummberOfGuests;
    }


    @DynamoDBHashKey(attributeName = "reservationId")
    @DynamoDBAutoGeneratedKey
    public String getReservationId() {
        return reservationId;
    }

    public void setReservationId(String reservationId) {
        this.reservationId = reservationId;
    }

    @DynamoDBAttribute
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute
    public String getTokenId() {
        return tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    @DynamoDBAttribute
    public String getNummberOfGuests() {
        return nummberOfGuests;
    }

    public void setNummberOfGuests(String nummberOfGuests) {
        this.nummberOfGuests = nummberOfGuests;
    }
    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
